### ISSUE TITLE
 msg: 'Error while creating the spot instance request: An error occurred (InvalidParameterValue) when calling the RequestSpotInstances operation: Invalid availability zone: [eu-west-2a]'

### ISSUE THREAD

**Issue by mihai-satmarean** [sharifkhan21/amazon-s3#1]
### Summary

when trying to deploy a spot instance with the following config:
```
    - name: Spot Request Creation with more options
      amazon.aws.ec2_spot_instance:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        launch_specification:
          image_id: "{{ image_id }}"
          key_name: "{{ key_name }}"
          instance_type: "{{ instance_type }}"
          placement:
            availability_zone: eu-west-2a
```

always gives the following error:

 `msg: 'Error while creating the spot instance request: An error occurred (InvalidParameterValue) when calling the RequestSpotInstances operation: Invalid availability zone: [eu-west-2a]'`

### Issue Type

Bug Report

### Component Name

amazon.aws.ec2_spot_instance

### Ansible Version

```console (paste below)
ansible 2.10.3
  config file = /Users/local//aws_cloud/ansible.cfg
  configured module search path = ['/Users/local/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.1 (default, Jan 30 2021, 15:51:05) [Clang 12.0.0 (clang-1200.0.32.29)]

```

### Collection Versions

```console (paste below)
# /Users/local/.ansible/collections/ansible_collections
Collection      Version
--------------- -------
amazon.aws      3.0.0
awx.awx         19.2.2
google.cloud    1.0.2
kubernetes.core 2.1.1
```

### AWS SDK versions

```console (paste below)
Name: boto
Version: 2.49.0
Summary: Amazon Web Services Library
Home-page: https://github.com/boto/boto/
Author: Mitch Garnaat
Author-email: mitch@garnaat.com
License: MIT
Location: /Users/local/Library/Python/2.7/lib/python/site-packages
Requires:
Required-by: molecule-ec2
---
Name: boto3
Version: 1.17.112
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: None
License: Apache License 2.0
Location: /Users/local/Library/Python/2.7/lib/python/site-packages
Requires: jmespath, s3transfer, botocore
Required-by: molecule-ec2
---
Name: botocore
Version: 1.20.112
Summary: Low-level, data-driven core of boto 3.
Home-page: https://github.com/boto/botocore
Author: Amazon Web Services
Author-email: None
License: Apache License 2.0
Location: /Users/local/Library/Python/2.7/lib/python/site-packages
Requires: jmespath, urllib3, python-dateutil
Required-by: s3transfer, boto3
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

macosx 10.15.7

### Steps to Reproduce

```yaml (paste below)
    - name: Spot Request Creation with more options
      amazon.aws.ec2_spot_instance:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        launch_specification:
          image_id: "{{ image_id }}"
          key_name: "{{ key_name }}"
          instance_type: "{{ instance_type }}"
          placement:
            availability_zone: eu-west-2a
```

### Expected Results

I expect a spot instance to be created

### Actual Results

```console (paste below)
 msg: 'Error while creating the spot instance request: An error occurred (InvalidParameterValue) when calling the RequestSpotInstances operation: Invalid availability zone: [eu-west-2a]'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
